language: node_js
node_js:
- '8.11.3'

branches:
  only:
    - develop

cache:
  directories:
    - node_modules

before_script:
  - npm install 

script:
  - npm run build

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: public
  skip_cleanup: true
  on:
    repo: karthikbalajikb/kbtechspace-site
  bucket: dev.kbtechspace.com
  region: us-east-1
